#!/usr/bin/env cargo-script
---
[dependencies]
anyhow = "1"
toml = "0.7"
dirs = "4"
which = "8"
fs_extra = "1.3.0"
---

use anyhow::{Context, Result};
use std::{env, fs, path::Path, process::Command};

fn main() -> Result<()> {
    println!("📖 Generating documentation...\n");

    let project_root = env::current_dir()?;

    let cargo_toml = fs::read_to_string("Cargo.toml").context("Failed to read Cargo.toml")?;
    let cargo_value: toml::Value = toml::from_str(&cargo_toml)?;
    let version = cargo_value
        .get("package")
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");

    println!("Library Version: {}\n", version);

    let docs_lib = Path::new("docs/lib");
    if docs_lib.exists() {
        fs::remove_dir_all(docs_lib)?;
    }
    fs::create_dir_all(docs_lib)?;

    if which::which("cargo").is_err() {
        println!("[FAILED] cargo not found - cannot generate documentation");
        println!("Please install Rust from https://rustup.rs/");
        return Ok(());
    }

    println!("════════════════════════════════════════════════════════════");
    println!("Generating API Documentation");
    println!("════════════════════════════════════════════════════════════\n");

    let target_dir = "./target/doc-build";
    let status = Command::new("cargo")
        .args(&[
            "doc",
            "--no-deps",
            "--all-features",
            "--target-dir",
            target_dir,
        ])
        .status()
        .context("Failed to run cargo doc")?;
    if !status.success() {
        anyhow::bail!("cargo doc failed");
    }

    let doc_source = Path::new(target_dir).join("doc");
    fs_extra::dir::copy(
        &doc_source,
        docs_lib,
        &fs_extra::dir::CopyOptions::new()
            .overwrite(true)
            .copy_inside(true),
    )
    .context("Failed to copy documentation to docs/lib")?;

    let index_html = docs_lib.join("index.html");
    let redirect_html = r#"<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="refresh" content="0; url=note/index.html">
    <title>Redirecting...</title>
</head>
<body>
    <p>Redirecting to <a href="note/index.html">documentation</a>...</p>
</body>
</html>
"#;
    fs::write(index_html, redirect_html)?;

    println!("\n[SUCCESS] Documentation generated successfully!");
    println!("\nDocumentation Location:\n  docs/lib/index.html");
    println!("\nTo view locally:");
    println!("  open docs/lib/index.html");
    println!("  Or start a local server:");
    println!("  cd docs && python3 -m http.server 8000");
    println!("  Then open: http://localhost:8000/lib/\n");
    println!("To publish to GitHub Pages:");
    println!("  git add docs/");
    println!("  git commit -m 'Update documentation'");
    println!("  git push\n");
    println!("Note: Swift and Kotlin bindings are auto-generated by UniFFI.");
    println!("This Rust documentation is the source of truth for the API.\n");

    Ok(())
}
